### ISSUE TITLE
Body needs holes for ports

### ISSUE THREAD

**Issue by runger1101001** [rosmo-robot/Rosmo_3D#1]
I think I understand how the ESC PCB would attach to the body... so it would be screwed on directly to the body, and not have its own "shell". In this case, the ports need to be modelled into the body:

- USB
- Grove port
- 2xSPI (JST SH 6 pin)
- 2 pin PWR terminal
- 2x 3 pin motor phases

**Comment by samuk** [comment]
Hmm I was imagining we would do it a 'shell' of it's own. I guess we'd need one for other use cases beyond the simple diffdrive in any case?

**Comment by runger1101001** [comment]
Ok, in this case the design needs some updating. 

The way m5 stack works, what I consider the "top" of the PCB is actually the bottom. So if you look at the ODrive module for example, the white side of the PCB (the flat side with the low connector) faces upwards and attaches to the Core module.
The black side of the PCB, with most of the components and all the headers/plugs on it, faces down. So the plugs are actually "upside down" when looking at the core module's screen.

For our design this means the top of the ESC is the side with the MCU, which will face the m5 core. The driver ICs and plugs are on the bottom side.

When you attach this PCB to the 3D designed base, the plugs would stick down into the base. If you turned it around, the m5 core would be inside the base, that wouldn't work.

Or if you made its own shell for the ESC, then there would need to be different attachment on the base. The PCB would then be 1cm above the base, and the shell of the ESC would connect to the base. Normally this connection would be via the m5 header, so the Rosmo base would need a different way to attach to the ESC-shell in this case.

**Comment by samuk** [comment]
Yes makes sense. Let's see if we can attach a shell to the body. We might be able to add some press fit 'tabs' that protrude up from the body and click into corresponding holes on our ESC case? Or maybe the holes are in the tabs and the ESC case has some pin/ lumps that it mates up too?

**Comment by samuk** [comment]
Will re-open as a 'tab' issue
