### ISSUE TITLE
Add lego profile to part of chassis

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/Rosmo_3D#10]
![rosmo-m5 (2)](https://user-images.githubusercontent.com/400875/150034200-2641e291-f6b4-412b-b849-c4231c38cce4.jpg)

If we add [Lego](https://www.thingiverse.com/thing:615256/files) bumps to this part of the chassis we could clip servos to the side of it.

**Comment by samuk** [comment]
@sathya131295 are you interested in doing this? The use case would be to attach small servos to convert into a walking robot.

**Comment by sathya131295** [comment]
Can do.

**Comment by sathya131295** [comment]
@samuk Adding lego dots wont be an issue, but if the print orientation is not vertical, it might not fit well. 

This orientation will work
![Screenshot 2022-01-20 131335](https://user-images.githubusercontent.com/69106463/150294999-9f97cd55-1a8c-439c-8cff-9c49104663e9.jpg)

This orientation might not work
![Screenshot 2022-01-20 131403](https://user-images.githubusercontent.com/69106463/150295002-5f91e25c-1d04-4091-a314-41883e5823b4.jpg)

**Comment by samuk** [comment]
Could you expand on this? 
Is it that;

If attached to the side of the robot the lego connection will have an insufficient force to hold a lego piece? Because 3dprint lego doesn't fit well? 

Or is it another issue I'm not understanding?

**Comment by sathya131295** [comment]
Yeah, 3D printed lego connection won't be that strong. Also, anything mounted on the side will be a cantilever.

**Comment by samuk** [comment]
OK thanks. Let's scrap that idea.
