### ISSUE TITLE
Reduce size of front 'connector' to fit bearing & lego

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/Rosmo_3D#11]
![IMG_20220119_143819](https://user-images.githubusercontent.com/400875/150152979-58e54ee5-fceb-4890-ae0d-d457938c3969.jpg)

This part is too large for bearing.

It is also too large for lego as discussed in other ticket.

**Comment by sathya131295** [comment]
Reduced the dia by 0.5mm and added a draft angle of 1 degree.

**Comment by samuk** [comment]
<img width="76" alt="check" src="https://user-images.githubusercontent.com/400875/150229206-cfa3b86a-39da-4e92-baa0-a7ee8fcd564e.png">

Can you double-check this part, please? Looks like we may have gone too small for a press fit in the bearing?

**Comment by sathya131295** [comment]
The shaft dia is correct, i imported the wrong bearing design, will fix it now.

**Comment by sathya131295** [comment]
Please verify now.

**Comment by samuk** [comment]
Nice.
