### ISSUE TITLE
Enlarge front bearing hole on robot body

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/Rosmo_3D#12]
The bearing (as specced on https://rosmo.io) is too large to fit into the robot body.

![IMG_20220119_143618](https://user-images.githubusercontent.com/400875/150153706-f13f67c8-76ec-4392-a0d2-cd78efee57a6.jpg)

**Comment by sathya131295** [comment]
Updated with 17.5mm Dia

**Comment by samuk** [comment]
Nice thanks :)
