### ISSUE TITLE
Create case for Rosmo ESC

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/Rosmo_3D#2]
Create a M5 stack case for https://github.com/rosmo-robot/Rosmo_ESC

This case may be a useful start: https://www.thingiverse.com/thing:2754642

The case should include a mechanism for secure attachment to the main body of the robot. The ESC case should be stackable with other ESC cases, or other M5 modules. 

Tabs/clips may need to be added to the main robot body. Or additional sockets added to accept clips. https://www.sculpteo.com/blog/2018/04/25/how-to-connect-two-parts-with-3d-printed-joints-and-snap-fits/

**Comment by samuk** [comment]
@sathya131295 Here's the .step file: https://github.com/rosmo-robot/Rosmo_ESC/issues/8#issuecomment-1004401861

**Comment by runger1101001** [comment]
Hey @sathya131295 , you're working in fusion 360? I have a license... is it possible that you share the fusion design so I could open it too? We've been doing it via files but it would be much cooler to have the updates via the cloud, so to speak... read-only would be fine...

**Comment by sathya131295** [comment]
https://a360.co/3Gckw9p ,here is the link.

**Comment by samuk** [comment]
Please see https://github.com/rosmo-robot/Rosmo_3D/new/main/V2
