### ISSUE TITLE
Create 'open wheel' for certification

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/Rosmo_3D#5]
For certifying the robot as OSHW we can't use any proprietary components such as lego. Therefore we should create a simple wheel of the same diameter as the lego one, which can be screwed directly to the motor.

**Comment by sathya131295** [comment]
Sure

**Comment by sathya131295** [comment]
Open wheels: https://a360.co/3AesEEg

**Comment by samuk** [comment]
Looks great, Thanks!
