### ISSUE TITLE
Part "Connector" is too fine

### ISSUE THREAD

**Issue by runger1101001** [rosmo-robot/Rosmo_3D#8]
Hey, on this part:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/7306964/148844364-e8a3e149-df10-4660-be10-043b769943a1.png">

the centre post is very fine. We'd be screwing an M2 screw into a very narrow, tall shape, and the distance to the edge as you see in the pic is only 0.6mm. I think my printer will produce this piece, but it will break for sure. Things will go better if one inserts the connector into the sprocket (which will then hold it together) first, before the screw, but my prediction is it will still break.

I would suggest a different approach: use the m2 screws, but go through the big holes on the sprocket. You could use 3 screws, that should be plenty. The connector can have 3 mating parts which extend into the holes and guide the screws.

And while it is possible to screw an M screw directly into printed plastic, and it will hold quite well, the caveat is that this works only once. If you unscrew it and re-screw it, the connection will no longer be good. So to enable a robot that people can assemble and disassemble multiple times I would strongly urge the use of (sunken) nuts rather than screwing into the plastic.
I use square nuts which look cool, but are also less likely to "strip" the plastic than hexagonal ones because they're less round. You just make a square pocket for the nut at the end of the screw hole.

The other thing I do is use threaded inserts which you sink into a correctly sized hole in the plastic using a soldering iron. The screws can then be nicely screwed in and out of the insert. But this is definately a bit harder, requires the soldering iron, and the inserts cost a lot more than the square nuts which cost next to nothing.

**Comment by sathya131295** [comment]
Thank you for noticing. Look at the updated designs for "Connector" and "Connector2" here: https://a360.co/3Gckw9p
Let me know your view.

**Comment by samuk** [comment]
Looks great, thanks
