### ISSUE TITLE
Reduce size of 'rear connector' to correspond to lego hole

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/Rosmo_3D#9]
<img width="46" alt="legoaxle" src="https://user-images.githubusercontent.com/400875/150031774-eb9f8ae9-ae61-4d7e-9a84-0dc5ea009f69.png">

The connector part is too large and does not fit into the wheel

**Comment by sathya131295** [comment]
-0.5mm reduction on all sides would do?

**Comment by samuk** [comment]
Yes i think so.

**Comment by samuk** [comment]
The circular part could do with being around 1mm thicker too I think to give clearance between lego sprocket and robot body
![IMG_20220119_091617](https://user-images.githubusercontent.com/400875/150101118-4aeea76b-4388-4585-8560-9c2fa3c0f577.jpg)

![IMG_20220119_091623](https://user-images.githubusercontent.com/400875/150101152-70495204-e73e-4c19-aa5a-95a584475a73.jpg)

**Comment by runger1101001** [comment]
hey, as an aside comment, for my 3D-printable designs with press-fitting parts or screw-holes, I always introduce a parameter (I call it "tolerance" but I'm sure there's a better name).
I use this parameter on all the close-fitting parts, either adding or subtracting it from the dimension involved. Then I can adapt the model to new 3D printers or filaments just by changing one parameter.

I have 3 printers and like to try different materials now and then. And I can tell you that each printer and material have slightly different properties regarding dimensional accuracy.

0.5mm is the kind of tolerance that needs to be changed depending on the printer, filament and how "tight" you want the fit to be. Depending on these things I might set it to 0.0, 0.25, or even 0.8...

Often I will then export a series of STLs with slightly changed tolerance settings, print them all, and see which fits best...

**Comment by samuk** [comment]
![IMG_20220119_143713](https://user-images.githubusercontent.com/400875/150152494-46fc15da-f02c-4301-9f43-565dd1b29fbe.jpg)

This connector should match the front connector in terms of depth? So that front and rear wheels align

**Comment by sathya131295** [comment]
@runger1101001 Yes, I too call it "tolerance",  a well calibrated printer can do with 0.2mm tolerance is guess.
@samuk I shall increase the size of all the slots by 0.5mm.

**Comment by sathya131295** [comment]
Added some clearance for "rear connector"
